# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine38"
  config.vm.hostname = "alpine"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "256"
  end
end
