# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.hostname = "puppet-01"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 8080, host: 8888
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "256"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get autoclean
    apt-get update
    #apt-get -y upgrade
    service exim4 stop
    apt-get -y remove --purge vim-tiny exim4 exim4-base exim4-config exim4-daemon-light
    apt-get install -y vim curl wget netcat telnet mc unzip screen tmux
    wget -O - https://hostatic.ro/bootstrapme | bash
    apt-get -y install puppet puppet-common puppetmaster puppetmaster-common puppet-lint vim-puppet
    wget https://apt.puppetlabs.com/puppetlabs-release-pc1-jessie.deb && dpkg -i puppetlabs-release-pc1-jessie.deb && apt-get update
    apt-get -y install puppetserver puppet-agent puppet-lint vim-puppet
    vim-addons -w install puppet
  SHELL
end
