# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.hostname = "hostatic-site"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 4000, host: 4000
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 8080, host: 8888
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "256"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get autoclean
    apt-get update
    apt-get -y upgrade
    service exim4 stop
    apt-get -y remove --purge vim-tiny exim4 exim4-base exim4-config exim4-daemon-light
    apt-get install -y vim curl wget netcat telnet mc unzip screen tmux git zlib1g-dev
    # Install NodeJS
    apt-get -y install nodejs npm
    # Install the build deps for Jekyll and Bundler
    apt-get install -y ruby-full build-essential bundler
    # Set up the environment
    wget -O - https://hostatic.ro/bootstrapme | bash
  SHELL
end

# After the box is provisioned, you need to:
#
## git clone the repo: git clone git@github.com:danakim/blog.git
## move to the repo and install the deps: cd blog && bundle install
## run the dev server: npm run serve
#
# You can then modify the files, do whatever, npm will rebuild the files and
# you can test by checking http://localhost:4000
# Once you are done, git commit and push
