# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "ubuntu-xenial"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 8082, host: 8082
  config.vm.network "forwarded_port", guest: 9090, host: 9090
  #config.vm.network "private_network", ip: "192.168.33.10"
  #config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get autoclean
    apt-get update
    #apt-get -y upgrade
    service exim4 stop
    apt-get -y remove --purge vim-tiny exim4 exim4-base exim4-config exim4-daemon-light
    apt-get install -y vim curl wget netcat telnet mc unzip screen tmux git
    wget -O - https://hostatic.ro/bootstrapme | bash
  SHELL
end
