# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "debian/jessie64"
    master.vm.hostname = 'master'
    master.vm.network "public_network", bridge: [
      "en0: Wi-Fi (AirPort)",
      "en1: Thunderbolt 1",
      "en2: Thunderbolt 2",
    ]

    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    master.vm.provision "shell", inline: <<-SHELL
      apt-get autoclean
      apt-get update
      #apt-get -y upgrade
      service exim4 stop
      apt-get -y remove --purge vim-tiny exim4 exim4-base exim4-config exim4-daemon-light
      apt-get install -y vim curl wget netcat telnet mc unzip screen tmux git
      wget --quiet -O - https://hostatic.ro/bootstrapme | bash
    SHELL
  end

  config.vm.define "worker" do |worker|
    worker.vm.box = "debian/jessie64"
    worker.vm.hostname = 'worker'
    worker.vm.network "public_network", bridge: [
      "en0: Wi-Fi (AirPort)",
      "en1: Thunderbolt 1",
      "en2: Thunderbolt 2",
    ]

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    worker.vm.provision "shell", inline: <<-SHELL
      apt-get autoclean
      apt-get update
      #apt-get -y upgrade
      service exim4 stop
      apt-get -y remove --purge vim-tiny exim4 exim4-base exim4-config exim4-daemon-light
      apt-get install -y vim curl wget netcat telnet mc unzip screen tmux git
      wget --quiet -O - https://hostatic.ro/bootstrapme | bash
    SHELL
  end
end
